modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/NicosaurusRex99/JARMGit/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/NicosaurusRex99/JARMGit/master/jarm_update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/jarm-just-another-ruby-mod/files"
logoFile="ruby.png"
authors="${mod_authors}"
description='''${mod_description}'''